-- MySQL Script generated by MySQL Workbench
-- Sat Apr  7 23:28:19 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Change History --------------------------------------
-- -----------------------------------------------------
-- 2018-05-08 ver0.5
--    1. Add two columns in article table.
--        `internel_fid` VARCHAR(100) NOT NULL COMMENT '内部存储的fid'
--        `internel_size` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '内部存储的size'
--    2. Modify columns in article_pending table.
--          ADD COLUMN `article_url` VARCHAR(1000) NOT NULL COMMENT '文章原文url地址',
--          CHANGE `article_url` `internel_fid` VARCHAR(100);
--          MODIFY `internel_fid` VARCHAR(100) NOT NULL COMMENT '内部存储的fid';
--          ADD COLUMN `internel_size` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '内部存储的size';
--          ADD COLUMN `internel_url` VARCHAR(1000) NOT NULL COMMENT '内部URL地址';
--
-- 2018-05-05 ver0.4
--    1. Add three columns in article table.
--         `content_type` VARCHAR(20) NOT NULL DEFAULT 'HTML' COMMENT '文章内容格式，枚举：HTML、MD、TXT'
--         `images` VARCHAR(4096) COMMENT '文章摘要图片，jsons数组格式';
--         `preview_layout` VARCHAR(20) NOT NULL DEFAULT 'TXT' COMMENT '预览布局，枚举：TXT(纯文字)、PIC-TXT-TB(图文混排上下)、PIC-TXT-LR(图文混排左右)';
--
-- 2018-04-24 ver0.3
--    1. Add AUTO_INCREMENT to id field of all tables.
--    2. Add UNSIGNED to int field.
-- -----------------------------------------------------


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema applet.geekapp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `applet.geekapp` ;

-- -----------------------------------------------------
-- Schema applet.geekapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `applet.geekapp` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `applet.geekapp` ;

-- -----------------------------------------------------
-- Table `applet.geekapp`.`wechat_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `applet.geekapp`.`wechat_user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `applet.geekapp`.`wechat_user` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '表自增ID',
  `open_id` VARCHAR(45) NOT NULL COMMENT '用户在微信的OpenId',
  `nick_name` VARCHAR(45) NOT NULL COMMENT '用户昵称',
  `avatar_url` VARCHAR(1000) NULL COMMENT '用户头像，最后一个数值代表正方形头像大小（有0、46、64、96、132数值可选，0代表640*640正方形头像），用户没有头像时该项为空。若用户更换头像，原有头像URL将失效。',
  `gender` VARCHAR(45) NOT NULL DEFAULT 0 COMMENT '用户的性别，值为1时是男性，值为2时是女性，值为0时是未知',
  `city` VARCHAR(60) NULL COMMENT '用户所在城市',
  `province` VARCHAR(60) NULL COMMENT '用户所在省份',
  `country` VARCHAR(45) NULL COMMENT '用户所在国家',
  `language` VARCHAR(45) NOT NULL DEFAULT 'zh_CN' COMMENT '用户的语言，简体中文为zh_CN',
  `is_del` VARCHAR(4) NOT NULL DEFAULT 'NO' COMMENT '是否删除标记，枚举类型：YES、NO，默认值NO。',
  `category_orders` VARCHAR(1000) NULL COMMENT '用户搜藏目录的顺序，存放category.id值，用逗号隔开',
  `gmt_create` DATETIME NOT NULL COMMENT '记录创建时间',
  `gmt_update` DATETIME NOT NULL COMMENT '记录更新时间',
  `create_user` VARCHAR(100) NULL COMMENT '记录创建人，格式为前缀+创建人ID，前缀为2字节，微信为we开头',
  `update_user` VARCHAR(100) NULL COMMENT '更新人',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户信息表';

SHOW WARNINGS;
CREATE UNIQUE INDEX `open_id_UNIQUE` ON `applet.geekapp`.`wechat_user` (`open_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `applet.geekapp`.`article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `applet.geekapp`.`article` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `applet.geekapp`.`article` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '表自增ID',
  `article_title` VARCHAR(1000) NOT NULL COMMENT '文章标题',
  `article_from` VARCHAR(255) NULL COMMENT '文章来源',
  `content_type` VARCHAR(20) NOT NULL DEFAULT 'HTML' COMMENT '文章内容格式，枚举：HTML、MD、TXT',
  `article_url` VARCHAR(1000) NOT NULL COMMENT '文章原文url地址',
  `internel_fid` VARCHAR(100) NOT NULL COMMENT '内部存储的fid',
  `internel_url` VARCHAR(1000) NOT NULL COMMENT '内部存储URL地址',
  `internel_size` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '内部存储的size',
  `images` VARCHAR(4096) COMMENT '文章摘要图片，jsons数组格式',
  `preview_layout` VARCHAR(20) NOT NULL DEFAULT 'TXT' COMMENT '预览布局，枚举：TXT(纯文字)、PIC-TXT-TB(图文混排上下)、PIC-TXT-LR(图文混排左右)',
  `article_labels` VARCHAR(1000) NULL COMMENT '分支分类标签，可多个用竖线(|)隔开。',
  `article_keywords` VARCHAR(1000) NULL COMMENT '文章关键词，文章中提到的重要知识点、名词术语、人或物、重要时间节点',
  `favorite_times` UNSIGNED INT(10) NULL DEFAULT 0 COMMENT '点赞总数',
  `view_times` INT(10) UNSIGNED NULL DEFAULT 0 COMMENT '浏览总数',
  `mark_times` INT(10) UNSIGNED NULL DEFAULT 0 COMMENT '收藏总数',
  `is_technology` VARCHAR(4) NOT NULL DEFAULT 'NO' COMMENT '表示是否技术文章，枚举类型：YES、NO，默认值NO，article_labels字段内会包含“技术”、”Tech“关键词和这边YES意思一致。',
  `is_blockchain` VARCHAR(4) NOT NULL DEFAULT 'NO' COMMENT '表示是否是区块链文章，枚举类型：YES、NO，默认值NO，article_labels字段内会包含“区块链”、”Blockchain“关键词和这边YES意思一致。',
  `state` VARCHAR(45) NULL COMMENT '文章状态，枚举类型：\nOFFLINE(下线),\nONLINE(上线),\nEDIT(编辑),\nDELETED(删除)',
  `comment` VARCHAR(200) NULL COMMENT '文章状态变化说明，如下线的原因',
  `gmt_create` DATETIME NOT NULL COMMENT '记录创建时间',
  `gmt_update` DATETIME NOT NULL COMMENT '记录更新时间',
  `create_user` VARCHAR(100) NULL COMMENT '记录创建人，格式为前缀+创建人ID，前缀为2字节，微信为we开头',
  `update_user` VARCHAR(100) NULL COMMENT '更新人',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '文章信息表';

SHOW WARNINGS;
CREATE UNIQUE INDEX `is_blockchain_UNIQUE` ON `applet.geekapp`.`article` (`is_blockchain` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `applet.geekapp`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `applet.geekapp`.`category` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `applet.geekapp`.`category` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '表自增ID',
  `user_id` BIGINT(20) UNSIGNED NOT NULL COMMENT 'wechat_user.id\n',
  `category_name` VARCHAR(45) NOT NULL COMMENT '目录名',
  `description` VARCHAR(500) NULL COMMENT '描述',
  `article_count` INT(10) NOT NULL DEFAULT 0 COMMENT '文章收藏数量',
  `is_del` VARCHAR(4) NULL DEFAULT 'NO' COMMENT '是否删除标记，枚举类型：YES、NO，默认值NO。',
  `gmt_create` DATETIME NOT NULL COMMENT '记录创建时间',
  `gmt_update` DATETIME NOT NULL COMMENT '记录更新时间',
  `create_user` VARCHAR(100) NULL COMMENT '记录创建人，格式为前缀+创建人ID，前缀为2字节，微信为we开头',
  `update_user` VARCHAR(100) NULL COMMENT '更新人',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '搜藏类目表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `applet.geekapp`.`article_favorite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `applet.geekapp`.`article_favorite` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `applet.geekapp`.`article_favorite` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '表自增ID',
  `article_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '文章Id，article.id',
  `user_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '用户ID，wechat_user.id\n',
  `gmt_create` DATETIME NOT NULL COMMENT '记录创建时间',
  `gmt_update` DATETIME NOT NULL COMMENT '记录更新时间',
  `create_user` VARCHAR(100) NULL COMMENT '记录创建人，格式为前缀+创建人ID，前缀为2字节，微信为we开头',
  `update_user` VARCHAR(100) NULL COMMENT '更新人',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '文章点赞记录表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `applet.geekapp`.`article_share`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `applet.geekapp`.`article_share` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `applet.geekapp`.`article_share` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '表自增ID',
  `article_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '文章Id，article.id',
  `user_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '用户ID，wechat_user.id\n',
  `gmt_create` DATETIME NOT NULL COMMENT '记录创建时间',
  `gmt_update` DATETIME NOT NULL COMMENT '记录更新时间',
  `create_user` VARCHAR(100) NULL COMMENT '记录创建人，格式为前缀+创建人ID，前缀为2字节，微信为we开头',
  `update_user` VARCHAR(100) NULL COMMENT '更新人')
ENGINE = InnoDB
COMMENT = '文章分享记录表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `applet.geekapp`.`article_pending`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `applet.geekapp`.`article_pending` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `applet.geekapp`.`article_pending` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '表自增ID',
  `article_title` VARCHAR(255) NOT NULL,
  `article_from` VARCHAR(255) NOT NULL,
  `internel_fid` VARCHAR(100) NOT NULL COMMENT '内部存储的fid',
  `internel_size` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '内部存储的size',
  `internel_url` VARCHAR(1000) NOT NULL COMMENT '内部URL地址',
  `article_keywords` VARCHAR(1000) NULL,
  `gmt_create` DATETIME NOT NULL COMMENT '记录创建时间',
  `gmt_update` DATETIME NOT NULL COMMENT '记录更新时间',
  `create_user` VARCHAR(100) NULL COMMENT '记录创建人，格式为前缀+创建人ID，前缀为2字节，微信为we开头',
  `update_user` VARCHAR(100) NULL COMMENT '更新人',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '外部收集的还未处理的文章';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `applet.geekapp`.`article_mark`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `applet.geekapp`.`article_mark` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `applet.geekapp`.`article_mark` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '表自增ID',
  `article_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '文章Id，article.id',
  `user_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '用户ID，wechat_user.id\n',
  `category_id` BIGINT(20) UNSIGNED NULL COMMENT '搜藏所属类目，category.id',
  `gmt_create` DATETIME NOT NULL COMMENT '记录创建时间',
  `gmt_update` DATETIME NOT NULL COMMENT '记录更新时间',
  `create_user` VARCHAR(100) NULL COMMENT '记录创建人，格式为前缀+创建人ID，前缀为2字节，微信为we开头',
  `update_user` VARCHAR(100) NULL COMMENT '更新人')
ENGINE = InnoDB
COMMENT = '课程收藏表\n';

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
