-- MySQL Script generated by MySQL Workbench
-- Sat Apr  7 23:28:19 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Change History --------------------------------------
-- -----------------------------------------------------
-- 2018-05-05 ver0.4
--    1. Add three columns in article table.
--         `content_type` VARCHAR(20) NOT NULL DEFAULT 'HTML' COMMENT '文章内容格式，枚举：HTML、MD、TXT'
--         `images` VARCHAR(4096) COMMENT '文章摘要图片，jsons数组格式';
--         `preview_layout` VARCHAR(20) NOT NULL DEFAULT 'TXT' COMMENT '预览布局，枚举：TXT(纯文字)、PIC-TXT-TB(图文混排上下)、PIC-TXT-LR(图文混排左右)';
--
-- -----------------------------------------------------

USE `applet.geekapp`;
ALTER TABLE `applet.geekapp`.`article` ADD COLUMN `content_type` VARCHAR(20) NOT NULL DEFAULT 'HTML' COMMENT '文章内容格式，枚举：HTML、MD、TXT';
ALTER TABLE `applet.geekapp`.`article` ADD COLUMN `images` VARCHAR(4096) COMMENT '文章摘要图片，jsons数组格式';
ALTER TABLE `applet.geekapp`.`article` ADD COLUMN `preview_layout` VARCHAR(20) NOT NULL DEFAULT 'TXT' COMMENT '预览布局，枚举：TXT(纯文字)、PIC-TXT-TB(图文混排上下)、PIC-TXT-LR(图文混排左右)';
